// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // A URL do banco é lida via env("DATABASE_URL") no schema.prisma.
  // Não declarar datasource.url aqui evita o conflito de validação do Prisma 6+.
});